### ISSUE TITLE
Meta/main.yml issue

### ISSUE THREAD

**Issue by pgporada** [bertvv/ansible-dnsmasq#7]
I'm on Ansible 2.0.1.0 on Ubuntu 15.10 trying to provision some Centos7 nodes.

```
ERROR! 'version' is not a valid attribute for a RoleMetadata

The error appears to have been in '/opt/work-repos/phils-docker-swarm-vagrant-demo/ansible/roles/bertvv.dnsmasq/meta/main.yml': line 2, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
galaxy_info:
^ here
```

**Comment by bertvv** [comment]
`version:` is an unofficial field that is used by a third-party tool for managing role dependencies (`librarian-ansible`). Custom meta fields are no longer accepted in Ansible 2.0. See [ansible/ansible#13496](https://github.com/ansible/ansible/issues/13496) for more info.

The field is already deleted from HEAD, but apparently, I haven't released a new version with this change yet.

**Comment by pgporada** [comment]
@bertvv 
Would you be able to release a new version today?

**Comment by bertvv** [comment]
Done!

**Comment by pgporada** [comment]
You're the man @bertvv!
